version: 2
jobs:
  build:

    working_directory: ~/taxidobarba/backend

    docker:
      - image: circleci/openjdk:11-jdk-browsers

    steps:

      - checkout:
          path: ~/taxidobarba

      - restore_cache:
          key: taxidobarba/backend-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: taxidobarba/backend-{{ checksum "pom.xml" }}
      
      - run: mvn clean install
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/taxidobarba.jar
      
      - run: bash ~/taxidobarba/.circleci/setup-heroku.sh
      
      - add_ssh_keys:
          fingerprints:
            - $HEROKU_SSH_FINGERPRINT
            
      - deploy:
          name: Deploy to Heroku if tests pass and branch is master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git pull --rebase
              git checkout -b tempbranch
              git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/tempbranch
            fi